# generated by datamodel-codegen:
#   filename:  analytics-v1.yaml
#   timestamp: 2026-08-04T19:25:49+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: str = Field(..., description='Error code')
    message: str = Field(..., description='Human-readable error message')


class ResourceID(RootModel[UUID]):
    root: UUID = Field(..., description='A resource identifier')


class Property(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: ResourceID
    name: str = Field(..., description='Human-readable property name')
    contractID: ResourceID = Field(..., description='Billing and permissions scope')
    timezone: str | None = Field(
        None, description='IANA timezone name (e.g., Europe/Helsinki)'
    )
    createdAt: AwareDatetime = Field(
        ..., description='RFC 3339 timestamp', examples=['2006-01-02T15:04:05Z07:00']
    )
    updatedAt: AwareDatetime = Field(
        ..., description='RFC 3339 timestamp', examples=['2006-01-02T15:04:05Z07:00']
    )


class PropertyCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Human-readable property name')
    contractID: ResourceID = Field(..., description='Billing and permissions scope')
    timezone: str | None = Field(
        None, description='IANA timezone name (e.g., Europe/Helsinki)'
    )


class PropertiesList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[Property]
    cursor: str | None = Field(None, description='Cursor token for pagination')


class DeviceType(Enum):
    desktop = 'desktop'
    mobile = 'mobile'
    tablet = 'tablet'


class Event(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: ResourceID
    eventName: str = Field(
        ..., description='Name of the event (e.g., page_view, session_start)'
    )
    timestamp: AwareDatetime = Field(
        ...,
        description='RFC 3339 timestamp when event occurred',
        examples=['2006-01-02T15:04:05Z07:00'],
    )
    userID: str | None = Field(
        None, description='Client-supplied end-user or session identifier'
    )
    sessionID: str | None = Field(None, description='Session identifier')
    country: str | None = Field(None, description='ISO 3166-1 alpha-2 country code')
    deviceType: DeviceType | None = Field(None, description='Device type')
    pagePath: str | None = Field(None, description='Page path (e.g., /pricing)')
    properties: dict[str, str] | None = Field(
        None, description='Custom event properties'
    )


class EventInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    eventName: str = Field(
        ..., description='Name of the event (e.g., page_view, session_start)'
    )
    timestamp: AwareDatetime = Field(
        ...,
        description='RFC 3339 timestamp when event occurred',
        examples=['2006-01-02T15:04:05Z07:00'],
    )
    userID: str | None = Field(
        None, description='Client-supplied end-user or session identifier'
    )
    sessionID: str | None = Field(None, description='Session identifier')
    country: str | None = Field(None, description='ISO 3166-1 alpha-2 country code')
    deviceType: DeviceType | None = Field(None, description='Device type')
    pagePath: str | None = Field(None, description='Page path (e.g., /pricing)')
    properties: dict[str, str] | None = Field(
        None, description='Custom event properties'
    )


class EventIngestRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    events: list[EventInput] = Field(..., min_length=1)


class EventIngestResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accepted: int = Field(..., description='Count of events accepted for ingestion')


class EventsList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[Event]
    cursor: str | None = Field(None, description='Cursor token for pagination')


class Dimension(Enum):
    date = 'date'
    country = 'country'
    deviceType = 'deviceType'
    pagePath = 'pagePath'
    eventName = 'eventName'


class Metric(Enum):
    sessions = 'sessions'
    pageviews = 'pageviews'
    users = 'users'
    bounceRate = 'bounceRate'
    eventCount = 'eventCount'


class DateRange(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    startDate: date_aliased = Field(
        ..., description='Start date (YYYY-MM-DD)', examples=['2026-07-01']
    )
    endDate: date_aliased = Field(
        ..., description='End date (YYYY-MM-DD)', examples=['2026-07-31']
    )


class ReportFilter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dimension: Dimension
    eq: str | None = Field(None, description='Exact match filter value')
    in_: list[str] | None = Field(
        None, alias='in', description='Match any of the provided values'
    )


class ReportQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dimensions: list[Dimension] = Field(
        ..., description='Dimensions to group results by', min_length=1
    )
    metrics: list[Metric] = Field(..., description='Metrics to aggregate', min_length=1)
    dateRange: DateRange
    filters: list[ReportFilter] | None = Field(
        None, description='Filters to apply to the report'
    )
    limit: int | None = Field(1000, description='Maximum rows to return')


class ReportJobStatus(Enum):
    PENDING = 'PENDING'
    RUNNING = 'RUNNING'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'


class ReportJob(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: ResourceID
    propertyID: ResourceID
    status: ReportJobStatus
    query: ReportQuery = Field(..., description='Echo of the submitted report query')
    createdAt: AwareDatetime = Field(
        ..., description='RFC 3339 timestamp', examples=['2006-01-02T15:04:05Z07:00']
    )
    updatedAt: AwareDatetime = Field(
        ..., description='RFC 3339 timestamp', examples=['2006-01-02T15:04:05Z07:00']
    )
    completedAt: AwareDatetime | None = Field(
        None,
        description='RFC 3339 timestamp when job completed or failed',
        examples=['2006-01-02T15:04:05Z07:00'],
    )
    errorMessage: str | None = Field(
        None, description='Error message if status is FAILED'
    )


class ReportJobsList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[ReportJob]
    cursor: str | None = Field(None, description='Cursor token for pagination')


class ReportRow(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dimensions: dict[str, str] = Field(..., description='Dimension values for this row')
    metrics: dict[str, float] = Field(..., description='Metric values for this row')


class ReportResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reportID: ResourceID
    rows: list[ReportRow]
    cursor: str | None = Field(None, description='Cursor token for pagination')
    totalRows: int | None = Field(
        None, description='Total rows matching the report query across all pages'
    )


class Visualization(Enum):
    table = 'table'
    line = 'line'
    bar = 'bar'
    pie = 'pie'


class DashboardWidget(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: ResourceID | None = Field(None, description='Server-assigned widget identifier')
    title: str = Field(..., description='Widget title')
    reportQuery: ReportQuery
    visualization: Visualization | None = Field(
        'table', description='Visualization type'
    )


class Dashboard(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: ResourceID
    name: str = Field(..., description='Dashboard name')
    contractID: ResourceID
    widgets: list[DashboardWidget]
    createdAt: AwareDatetime = Field(
        ..., description='RFC 3339 timestamp', examples=['2006-01-02T15:04:05Z07:00']
    )
    updatedAt: AwareDatetime = Field(
        ..., description='RFC 3339 timestamp', examples=['2006-01-02T15:04:05Z07:00']
    )


class DashboardCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Dashboard name')
    contractID: ResourceID
    widgets: list[DashboardWidget] = Field(..., min_length=1)


class DashboardUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = Field(None, description='Dashboard name')
    widgets: list[DashboardWidget] | None = None


class DashboardsList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[Dashboard]
    cursor: str | None = Field(None, description='Cursor token for pagination')
